language: rust
cache: cargo

dist: bionic

branches:
  only:
    - src

before_script:
  # Download and unzip the zola executable
  #- curl -s -L https://github.com/64/zola/releases/latest/download/zola.tar.gz | sudo tar xvzf - -C /usr/local/bin
  - git clone https://github.com/64/zola
  - cd zola && cargo build && cargo install --path .

script:
  - zola check
  - zola build

after_success: |
  [ $TRAVIS_BRANCH = src ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  zola build &&
  sudo pip install ghp-import &&
  ghp-import -b master -n public &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git master
