base_url = "https://64.github.io"
compile_sass = true
highlight_code = true
highlight_theme = "ayu-dark"
build_search_index = true
theme = "even"
title = "Zeta"
# check_external_links = true

taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[extra]
katex_enable = true
katex_auto_render = true
even_title = "Zeta - Blog by 64"
author = "64"

even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "https://github.com/64", name = "GitHub"},
]