base_url = "https://64.github.io"
compile_sass = true
highlight_code = true
highlight_theme = "ayu-dark"
build_search_index = true
theme = "even"
title = "Zeta"
# check_external_links = true

taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

[extra]
katex_enable = true
katex_auto_render = true
even_title = "Zeta - Blog by 64"
author = "64"
disqus_comment_code = "<div id=\"disqus_thread\"></div> <script>(function() { var d = document, s = d.createElement('script'); s.src = 'https://64-github-io.disqus.com/embed.js'; s.setAttribute('data-timestamp', +new Date()); (d.head || d.body).appendChild(s); })();</script> <noscript>Please enable JavaScript to view the <a href=\"https://disqus.com/?ref_noscript\">comments powered by Disqus.</a></noscript>"
#disqus_comment_count = "<script id=\"dsq-count-scr\" src=\"//64-github-io.disqus.com/count.js\" async></script>"

even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "https://github.com/64", name = "GitHub"},
]
